### ISSUE TITLE
Update theme to fit new design

### ISSUE THREAD

**Issue by devey** [curaOS/source#96]
Should be enough to adjust the `theme` file based on the new designs, but I guess needs to be done as components are added to not put too much effort intro changing the whole, imported ,`tailwind` base style we are using now.

* https://www.figma.com/file/ZEDDdXRTJxKZH5j5OvGOn4/CURA.RUN?node-id=0%3A1.

- [x] Define [Typography](https://theme-ui.com/theming/#typography) and make variants for text _**(#100)**_
- [x] Define [Colors](https://theme-ui.com/theming/#color-modes) for dark and light modes _**(#107)**_
- [x] Define buttons [Variants](https://theme-ui.com/guides/variants#variants)  _**(#123)**_

**Comment by devey** [comment]
Move to Epic.

**Comment by devey** [comment]
I think we can close this @achrafismyname ?

**Comment by achrafismyname** [comment]
Yes sure we can close it
Most things are done here but small tweaks will still be needed as we go with #98
